# Site settings
title: brewscheme
email: william@williambuchanan.net
description: Making it easier for you to generate the data visualizations you want from Stata less verbose, easier to reproduce, and more flexible for inclusion in production environments.
baseurl: "/brewscheme" # the subpath of your site, e.g. /blog/
url: "https://wbuchanan.github.io" # the base hostname & protocol for your site
twitter_username: PACESconsulting
github_username:  wbuchanan
encoding: utf-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

menu_generator:
  css:
    current: "current"
    current_parent: "current-parent"
  delete_content_hash: "false"
  hash_name_in_site_config: "menu"
  menu_root: "main"
  parent_match_hash: "path"


